// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: average.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAverageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAverageRequest) Reset() {
	*x = GetAverageRequest{}
	mi := &file_average_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAverageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAverageRequest) ProtoMessage() {}

func (x *GetAverageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_average_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAverageRequest.ProtoReflect.Descriptor instead.
func (*GetAverageRequest) Descriptor() ([]byte, []int) {
	return file_average_proto_rawDescGZIP(), []int{0}
}

func (x *GetAverageRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type GetAverageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Average       float64                `protobuf:"fixed64,1,opt,name=average,proto3" json:"average,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAverageResponse) Reset() {
	*x = GetAverageResponse{}
	mi := &file_average_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAverageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAverageResponse) ProtoMessage() {}

func (x *GetAverageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_average_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAverageResponse.ProtoReflect.Descriptor instead.
func (*GetAverageResponse) Descriptor() ([]byte, []int) {
	return file_average_proto_rawDescGZIP(), []int{1}
}

func (x *GetAverageResponse) GetAverage() float64 {
	if x != nil {
		return x.Average
	}
	return 0
}

var File_average_proto protoreflect.FileDescriptor

const file_average_proto_rawDesc = "" +
	"\n" +
	"\raverage.proto\x12\n" +
	"calculator\"+\n" +
	"\x11GetAverageRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\".\n" +
	"\x12GetAverageResponse\x12\x18\n" +
	"\aaverage\x18\x01 \x01(\x01R\aaverageB4Z2github.com/ftilie/go-grpc-servers/calculator/protob\x06proto3"

var (
	file_average_proto_rawDescOnce sync.Once
	file_average_proto_rawDescData []byte
)

func file_average_proto_rawDescGZIP() []byte {
	file_average_proto_rawDescOnce.Do(func() {
		file_average_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_average_proto_rawDesc), len(file_average_proto_rawDesc)))
	})
	return file_average_proto_rawDescData
}

var file_average_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_average_proto_goTypes = []any{
	(*GetAverageRequest)(nil),  // 0: calculator.GetAverageRequest
	(*GetAverageResponse)(nil), // 1: calculator.GetAverageResponse
}
var file_average_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_average_proto_init() }
func file_average_proto_init() {
	if File_average_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_average_proto_rawDesc), len(file_average_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_average_proto_goTypes,
		DependencyIndexes: file_average_proto_depIdxs,
		MessageInfos:      file_average_proto_msgTypes,
	}.Build()
	File_average_proto = out.File
	file_average_proto_goTypes = nil
	file_average_proto_depIdxs = nil
}
