// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: calculator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_calculator_proto protoreflect.FileDescriptor

const file_calculator_proto_rawDesc = "" +
	"\n" +
	"\x10calculator.proto\x12\n" +
	"calculator\x1a\tadd.proto\x1a\x0esubtract.proto\x1a\x0emultiply.proto\x1a\fdivide.proto\x1a\vprime.proto\x1a\raverage.proto\x1a\rmaximum.proto\x1a\n" +
	"sqrt.proto2\xd3\x04\n" +
	"\x11CalculatorService\x126\n" +
	"\x03Add\x12\x16.calculator.AddRequest\x1a\x17.calculator.AddResponse\x12E\n" +
	"\bSubtract\x12\x1b.calculator.SubtractRequest\x1a\x1c.calculator.SubtractResponse\x12E\n" +
	"\bMultiply\x12\x1b.calculator.MultiplyRequest\x1a\x1c.calculator.MultiplyResponse\x12?\n" +
	"\x06Divide\x12\x19.calculator.DivideRequest\x1a\x1a.calculator.DivideResponse\x12J\n" +
	"\tGetPrimes\x12\x1c.calculator.GetPrimesRequest\x1a\x1d.calculator.GetPrimesResponse0\x01\x12M\n" +
	"\n" +
	"GetAverage\x12\x1d.calculator.GetAverageRequest\x1a\x1e.calculator.GetAverageResponse(\x01\x12O\n" +
	"\n" +
	"GetMaximum\x12\x1d.calculator.GetMaximumRequest\x1a\x1e.calculator.GetMaximumResponse(\x010\x01\x12K\n" +
	"\n" +
	"SquareRoot\x12\x1d.calculator.SquareRootRequest\x1a\x1e.calculator.SquareRootResponseB4Z2github.com/ftilie/go-grpc-servers/calculator/protob\x06proto3"

var file_calculator_proto_goTypes = []any{
	(*AddRequest)(nil),         // 0: calculator.AddRequest
	(*SubtractRequest)(nil),    // 1: calculator.SubtractRequest
	(*MultiplyRequest)(nil),    // 2: calculator.MultiplyRequest
	(*DivideRequest)(nil),      // 3: calculator.DivideRequest
	(*GetPrimesRequest)(nil),   // 4: calculator.GetPrimesRequest
	(*GetAverageRequest)(nil),  // 5: calculator.GetAverageRequest
	(*GetMaximumRequest)(nil),  // 6: calculator.GetMaximumRequest
	(*SquareRootRequest)(nil),  // 7: calculator.SquareRootRequest
	(*AddResponse)(nil),        // 8: calculator.AddResponse
	(*SubtractResponse)(nil),   // 9: calculator.SubtractResponse
	(*MultiplyResponse)(nil),   // 10: calculator.MultiplyResponse
	(*DivideResponse)(nil),     // 11: calculator.DivideResponse
	(*GetPrimesResponse)(nil),  // 12: calculator.GetPrimesResponse
	(*GetAverageResponse)(nil), // 13: calculator.GetAverageResponse
	(*GetMaximumResponse)(nil), // 14: calculator.GetMaximumResponse
	(*SquareRootResponse)(nil), // 15: calculator.SquareRootResponse
}
var file_calculator_proto_depIdxs = []int32{
	0,  // 0: calculator.CalculatorService.Add:input_type -> calculator.AddRequest
	1,  // 1: calculator.CalculatorService.Subtract:input_type -> calculator.SubtractRequest
	2,  // 2: calculator.CalculatorService.Multiply:input_type -> calculator.MultiplyRequest
	3,  // 3: calculator.CalculatorService.Divide:input_type -> calculator.DivideRequest
	4,  // 4: calculator.CalculatorService.GetPrimes:input_type -> calculator.GetPrimesRequest
	5,  // 5: calculator.CalculatorService.GetAverage:input_type -> calculator.GetAverageRequest
	6,  // 6: calculator.CalculatorService.GetMaximum:input_type -> calculator.GetMaximumRequest
	7,  // 7: calculator.CalculatorService.SquareRoot:input_type -> calculator.SquareRootRequest
	8,  // 8: calculator.CalculatorService.Add:output_type -> calculator.AddResponse
	9,  // 9: calculator.CalculatorService.Subtract:output_type -> calculator.SubtractResponse
	10, // 10: calculator.CalculatorService.Multiply:output_type -> calculator.MultiplyResponse
	11, // 11: calculator.CalculatorService.Divide:output_type -> calculator.DivideResponse
	12, // 12: calculator.CalculatorService.GetPrimes:output_type -> calculator.GetPrimesResponse
	13, // 13: calculator.CalculatorService.GetAverage:output_type -> calculator.GetAverageResponse
	14, // 14: calculator.CalculatorService.GetMaximum:output_type -> calculator.GetMaximumResponse
	15, // 15: calculator.CalculatorService.SquareRoot:output_type -> calculator.SquareRootResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_calculator_proto_init() }
func file_calculator_proto_init() {
	if File_calculator_proto != nil {
		return
	}
	file_add_proto_init()
	file_subtract_proto_init()
	file_multiply_proto_init()
	file_divide_proto_init()
	file_prime_proto_init()
	file_average_proto_init()
	file_maximum_proto_init()
	file_sqrt_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calculator_proto_rawDesc), len(file_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculator_proto_goTypes,
		DependencyIndexes: file_calculator_proto_depIdxs,
	}.Build()
	File_calculator_proto = out.File
	file_calculator_proto_goTypes = nil
	file_calculator_proto_depIdxs = nil
}
