// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: maximum.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMaximumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMaximumRequest) Reset() {
	*x = GetMaximumRequest{}
	mi := &file_maximum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMaximumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaximumRequest) ProtoMessage() {}

func (x *GetMaximumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maximum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaximumRequest.ProtoReflect.Descriptor instead.
func (*GetMaximumRequest) Descriptor() ([]byte, []int) {
	return file_maximum_proto_rawDescGZIP(), []int{0}
}

func (x *GetMaximumRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type GetMaximumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Maximum       int32                  `protobuf:"varint,1,opt,name=maximum,proto3" json:"maximum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMaximumResponse) Reset() {
	*x = GetMaximumResponse{}
	mi := &file_maximum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMaximumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaximumResponse) ProtoMessage() {}

func (x *GetMaximumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_maximum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaximumResponse.ProtoReflect.Descriptor instead.
func (*GetMaximumResponse) Descriptor() ([]byte, []int) {
	return file_maximum_proto_rawDescGZIP(), []int{1}
}

func (x *GetMaximumResponse) GetMaximum() int32 {
	if x != nil {
		return x.Maximum
	}
	return 0
}

var File_maximum_proto protoreflect.FileDescriptor

const file_maximum_proto_rawDesc = "" +
	"\n" +
	"\rmaximum.proto\x12\n" +
	"calculator\"+\n" +
	"\x11GetMaximumRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\".\n" +
	"\x12GetMaximumResponse\x12\x18\n" +
	"\amaximum\x18\x01 \x01(\x05R\amaximumB4Z2github.com/ftilie/go-grpc-servers/calculator/protob\x06proto3"

var (
	file_maximum_proto_rawDescOnce sync.Once
	file_maximum_proto_rawDescData []byte
)

func file_maximum_proto_rawDescGZIP() []byte {
	file_maximum_proto_rawDescOnce.Do(func() {
		file_maximum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_maximum_proto_rawDesc), len(file_maximum_proto_rawDesc)))
	})
	return file_maximum_proto_rawDescData
}

var file_maximum_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_maximum_proto_goTypes = []any{
	(*GetMaximumRequest)(nil),  // 0: calculator.GetMaximumRequest
	(*GetMaximumResponse)(nil), // 1: calculator.GetMaximumResponse
}
var file_maximum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_maximum_proto_init() }
func file_maximum_proto_init() {
	if File_maximum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_maximum_proto_rawDesc), len(file_maximum_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_maximum_proto_goTypes,
		DependencyIndexes: file_maximum_proto_depIdxs,
		MessageInfos:      file_maximum_proto_msgTypes,
	}.Build()
	File_maximum_proto = out.File
	file_maximum_proto_goTypes = nil
	file_maximum_proto_depIdxs = nil
}
