// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: prime.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPrimesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrimesRequest) Reset() {
	*x = GetPrimesRequest{}
	mi := &file_prime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrimesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrimesRequest) ProtoMessage() {}

func (x *GetPrimesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrimesRequest.ProtoReflect.Descriptor instead.
func (*GetPrimesRequest) Descriptor() ([]byte, []int) {
	return file_prime_proto_rawDescGZIP(), []int{0}
}

func (x *GetPrimesRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type GetPrimesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prime         int32                  `protobuf:"varint,1,opt,name=prime,proto3" json:"prime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrimesResponse) Reset() {
	*x = GetPrimesResponse{}
	mi := &file_prime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrimesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrimesResponse) ProtoMessage() {}

func (x *GetPrimesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrimesResponse.ProtoReflect.Descriptor instead.
func (*GetPrimesResponse) Descriptor() ([]byte, []int) {
	return file_prime_proto_rawDescGZIP(), []int{1}
}

func (x *GetPrimesResponse) GetPrime() int32 {
	if x != nil {
		return x.Prime
	}
	return 0
}

var File_prime_proto protoreflect.FileDescriptor

const file_prime_proto_rawDesc = "" +
	"\n" +
	"\vprime.proto\x12\n" +
	"calculator\"*\n" +
	"\x10GetPrimesRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\")\n" +
	"\x11GetPrimesResponse\x12\x14\n" +
	"\x05prime\x18\x01 \x01(\x05R\x05primeB4Z2github.com/ftilie/go-grpc-servers/calculator/protob\x06proto3"

var (
	file_prime_proto_rawDescOnce sync.Once
	file_prime_proto_rawDescData []byte
)

func file_prime_proto_rawDescGZIP() []byte {
	file_prime_proto_rawDescOnce.Do(func() {
		file_prime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_prime_proto_rawDesc), len(file_prime_proto_rawDesc)))
	})
	return file_prime_proto_rawDescData
}

var file_prime_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_prime_proto_goTypes = []any{
	(*GetPrimesRequest)(nil),  // 0: calculator.GetPrimesRequest
	(*GetPrimesResponse)(nil), // 1: calculator.GetPrimesResponse
}
var file_prime_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_prime_proto_init() }
func file_prime_proto_init() {
	if File_prime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_prime_proto_rawDesc), len(file_prime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_prime_proto_goTypes,
		DependencyIndexes: file_prime_proto_depIdxs,
		MessageInfos:      file_prime_proto_msgTypes,
	}.Build()
	File_prime_proto = out.File
	file_prime_proto_goTypes = nil
	file_prime_proto_depIdxs = nil
}
